version: '3'

services:
  price_it_frontend:
    container_name: price_it_frontend
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${DOCKER_SERVER_PORT}:${LOCAL_SERVER_PORT}
    volumes:
      - .:/src
      - /src/node_modules